### ISSUE TITLE
Вылетает при обновлении оружия, при 3% загрузки

### ISSUE THREAD

**Issue by HologramIllusion** [MangriMen/TRND#12]

**Comment by HologramIllusion** [comment]
можешь ли помочь?

**Comment by MangriMen** [comment]
> можешь ли помочь?

В планах починить. Как будет свободное время постараюсь это сделать. Проблема в вёрстке вики откуда берутся данные, посмотрю в чём проблема либо попробую использовать другое api

**Comment by HologramIllusion** [comment]
понял буду ждать

**Comment by HologramIllusion** [comment]
как успехи друг?

**Comment by MangriMen** [comment]
> как успехи друг?

В процессе. Прошлую неделю болел поэтому пока прогресс не сильно, переписываю генератор под новое api

**Comment by MangriMen** [comment]
> как успехи друг?

Выложил релиз, пока не супер стабильно но пользоваться можно
